### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by DGUTdgut** [mandatoryprogrammer/xsshunter-express#21]
[root@iZt4ndkfpmx5eozp4q0aowZ xsshunter-express]# docker-compose up xsshunterexpress
Building xsshunterexpress
Sending build context to Docker daemon  66.14MB

Step 1/25 : FROM node:12
 ---> 6c8de432fc7f
Step 2/25 : RUN mkdir /app/
 ---> Using cache
 ---> 4abafa969f34
Step 3/25 : WORKDIR /app/
 ---> Using cache
 ---> 4794f390a553
Step 4/25 : COPY front-end/ /app/front-end/
 ---> Using cache
 ---> 73c41d33c9ff
Step 5/25 : WORKDIR /app/front-end/
 ---> Using cache
 ---> 02f480253d47
Step 6/25 : RUN npm install
 ---> Running in 71e72397d17f
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/vue-loader failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-11T14_33_26_267Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

**Comment by albertusfreddi** [comment]
heii i have some error here to, i got stuck in step 6 RUN npm install, do you solved it?? every i run that, and got hours and got hang
