### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1. For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

### ISSUE THREAD

**Issue by dasithsv** [mandatoryprogrammer/xsshunter-express#7]
im getting this error, while doing docker-compose up -d postgresdb

  ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
  For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by vansh1** [comment]
do you got solution for this ?
